---
- hosts: localhost
  roles:
  - role: nginx_proxy
    nginx_proxy_backends:
    - location: /
      server: http://localhost:8080
      cache_validity: 1h
    nginx_proxy_worker_processes: 4
    nginx_proxy_404: '/404.html'
    nginx_proxy_ssl: True
    nginx_proxy_ssl_certificate: /etc/nginx/ssl/website.crt
    nginx_proxy_ssl_certificate_key: /etc/nginx/ssl/website.key
    nginx_proxy_http2: True
    nginx_proxy_force_ssl: True
    nginx_proxy_hsts_age: 31536000
    nginx_proxy_conf_http:
      - "client_max_body_size 500m"
      - "server_tokens off"

#- hosts: jenkins
#  vars:
#    jenkins_package_state: present
#  roles:
#    - { role: geerlingguy.java, become: yes }
#      #become: true
