---
- hosts: localhost
  roles:
    - role: ypsman.nginx-proxy
      nginx_proxy_custom_index: index.html
      nginx_proxy_ssl_proxy: true                         		# Enable SSL
      nginx_proxy_ssl_cert: /etc/ssl/certs/nginx-selfsigned.crt         # Location ssl Cert File
      nginx_proxy_ssl_key: /etc/ssl/private/nginx-selfsigned.key        # Location ssl key File
      nginx_proxy_server_name: "{{ ansible_hostname }}" 		# Servername to listen on  
      nginx_proxy_pass: http://localhost:8080             		# Site to proxy
  become: true

